MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 5
    FPN_POST_NMS_TOP_N_TEST: 5
    
    NMS_THRESH: 0.8
    FG_IOU_THRESHOLD: 0.8
    BG_IOU_THRESHOLD: 0.3
    POSITIVE_FRACTION: 0.3
    MIN_SIZE: 20
    MAX_SIZE: (175,175)
  ROI_HEADS:
    USE_FPN: True
    OHEM: True
    DETECTIONS_PER_IMG: 1

  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 3
    CUSTOM_POSTPROCESS: True
    PROCESS_DARK: True
    PROCESS_SATURATED: True
DATASETS:
  TRAIN: ("cvc-colondb-train", "cvc-colondb-val")
  TEST: ("cvc-clinic-val", "cvc-clinic-test", )
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # 1 GPU
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: [0, 765, 1225]
  MAX_ITER: 1530 # 5 epochs
  IMS_PER_BATCH: 2
  SCHEDULER: "cosine"
OUTPUT_DIR: "results_october/tuned_colon"
INPUT:
  # Color Jitter
  HUE: 0.05
  BRIGHTNESS: 0.1
  SATURATION: 0.1
  CONTRAST: 0.1

  # Flips & sizes
  VERTICAL_FLIP_PROB_TRAIN: 0.4
  MIN_SIZE_TRAIN: (288, 384, )
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 384
  MAX_SIZE_TEST: 800

  # Affine transform
  PROB_AFFINE: 0.5
  SHEAR: (2,2)
  ROTATION: (-5, 5)
  TRANSLATION_FACTOR: (0.1,0.1)
  SCALE_FACTOR: (0.1,0.1)

  # Blurs
  PROB_GAUSSIAN_BLUR: 0.5
  BLUR_KERNEL_SIZE: [1, 2, 3]

TEST:
  IMS_PER_BATCH: 1
#  BBOX_AUG:
#    ENABLED: True
#    H_FLIP: True
