MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "catalog://Caffe2Detectron/COCO/35858933/e2e_mask_rcnn_R-50-FPN_1x"
  WEIGHT: "pretrained_models/mask_rcnn_R-50-FPN_1x_detectron_no_last_layers.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 64, 128)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 100
    POST_NMS_TOP_N_TEST: 100
    FPN_POST_NMS_TOP_N_TEST: 1000
    FG_IOU_THRESHOLD: 0.8

  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True

DATASETS:
  TRAIN: ("cvc-clinic-train",  "cvc-classification",)
  TEST: ("cvc-clinic-val", "etis-larib",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
# 1 GPU
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: [0, 3000, 4000]
  MAX_ITER: 10000
  IMS_PER_BATCH: 8
# 4 GPUs:
#  BASE_LR: 0.01
#  MAX_ITER: 15000
#  STEPS: [0, 7500, 10000]
#  IMS_PER_BATCH: 32
OUTPUT_DIR: "out/test_minsize_anchors"
INPUT:
  HUE: 0.15
  BRIGHTNESS: 0.05
  SATURATION: 0.05
  VERTICAL_FLIP_PROB_TRAIN: 0.4
  MIN_SIZE_TRAIN: (384,)
  MIN_SIZE_TEST: 384

